### ISSUE TITLE
Stuck at disclaimer screen

### ISSUE THREAD

**Issue by rawbertp** [xtech/self-o-mat#5] opened 2019-11-01 19:33 UTC
Sorry, if these are stupid questions but...  

1. Why does the window look like that (I cannot resize it, I cannot move it, I can do nothing with it)
2. How do I get beyond this disclaimer screen?

Screen resolution is 1920x1080.

![2019-11-01-202558_1920x1080_scrot](https://user-images.githubusercontent.com/12150805/68051112-e9668b00-fce6-11e9-9b74-6870534cffb7.png)

**Comment by lvillatoroq** [comment] 2019-11-27 10:23
I am having the same issue as well. Did you manage to go past this screen?

**Comment by rawbertp** [comment] 2019-11-27 10:26
Nope, sorry. I gave up. Since I didn't get a single response here for almost a month I consider that project dead.

**Comment by maehw** [comment] 2021-11-18 11:07
Hi. I know this issue is quite old, but there might still be people stumbling over this. I've also been trying to get thinks work for me - and also been stuck with the screen here first. I think you need to dive a bit into the source code to understand what's actually going on.

There must be a way to accept the agreement - probably by pressing the push button. As I do not have one (yet?), I was also looking for a way to prevent this.

As I've started with a single screen, first thing for me was to disable fullscreen mode: in your `./settings/<box_type>.json` set `"fullscreen": false`. You can always have a look at the console output (also setting `"debug": true` in the same file might be quite useful).

The code actually tries to read additional settings from `<HOME>/.selfomat_settings.json` and uses default values if the file dos not exist. You can:

* create the missing file (or modify the existing file) and set `"show_agreement": "false"` OR
* replace the `true` by `false` in `this->showAgreement = ptree.get<bool>("show_agreement", true);` (in the source code of `./src/logic/BoothLogic.cpp`) and rebuild and re-run the project

In my fork (https://github.com/maehw/self-o-mat) I've tried to document those undocumented things.

HTH

**Comment by ClemensElflein** [comment] 2021-11-18 17:06
Hi maehw,
thank you for writing this comment and for trying to get the self-o-mat software to work for you.

First of all, I'm sorry for the missing documentation and reactions on this project. I currently do not have the time to actively maintain it but I can assure you that the software works very stable, since it is deployed on many photobooths which are in active use. 

I am aware that the documentation is lacking and that the project therefore is currently hard to build using only open-source software. Since I have invested a lot of time into this project, and currently am not able to sell the photobooth kits anymore, it would be great to see that the the self-o-mat could live on as an open source project.

You are completely right: at the moment, you'd need the self-o-mat hardware to use the photobooth software as intended (and agree to the terms). You can build your own hardware using an Arduino. I have the firmware available somewhere.

If you are interested to go down this path and document the self-o-mat software, I'd be happy to share the Arduino schematics and software needed to get this to work. I'll also answer any questions so that you can get started as quickly as possible.

It would be great if you could write some documentation in exchange. Could we maybe try to keep the information in this repository's Wiki page?

**Comment by maehw** [comment] 2021-11-18 17:48
Hi Clemens,
thank you for your detailed and quick response.

It really looks like a neat project and I am happy to help here - as long as I have the time for it.
I think we can improve documentation and put in this (the original repo's) wiki. You may be required to create it first or somehow grant me access. As you're the original author/ software architect it would be great if you could answer some questions what might speed things up a bit. Where should I place them? Open another issue? In the wiki?
By the way: all in all, it's already great that you have shared this project as open source! :clap: I feel the energy that you have put into this project so far.
Regarding the hardware: do you have some more hardware lying around? Is it really required (that might already be one of the real next questions) - it seems that you can already trigger a photo by clicking in the preview windows instead of pressing a real hardware button.
By the way: I had a more complex DIY photo booth setup running but I want to replace it with less and newer hardware.

Cheers,
maehw

**Comment by ClemensElflein** [comment] 2021-11-18 18:39
Hi maehw,
sounds good! I have enabled the wiki and added you as a collaborator so you should have write access to the wiki now.

Sure, no pressure! If you don't have the time, it's no problem. I'm glad for every help that I can get.

As for the discussions, I think we should try the GitHub discussions page. I have also enabled the feature for this repo. This way other people can read the messages and maybe can get some info out of it. The only drawback that I see is that I don't get a push message to my desktop for GitHub notifications and I check my emails once a day at most. I'll get the GitHub mobile app and try to answer in a timely manner.
Would this be alright for you or do you have another idea how we could handle discussions better? An open discord server is another alternative that I can think of, but I don't know if that's worth for two people..

Regarding hardware:
The hardware part of the photobooth is basically a quality of life upgrade. It is intended to make building a photobooth very simple:
- The hardware is originally designed as RasperryPi add-on board.
- It has 12V input and a 5V step down converter. Therefore the whole self-o-mat can be powered using one single 12V power supply rather than with multiple PSUs (5V for the Pi, 12V for the screen)
- It has its own (always on) microcontroller which allows the board to cut the power to the RaspberryPi, the screen and optionally a camera / other external hardware.
- Additionally, the external microcontroller allows us to play smooth animations on the NeoPixel easily. There are animations for booting, printing, count down, ready to take a photo and update / error states.
- Unfortunately I do not have spare hardware, sorry.



>  By the way: I had a more complex DIY photo booth setup running but I want to replace it with less and newer hardware.

This is exactly why I created the project in the first place. Existing photobooth setups seemed overly complicated, expensive and buggy.

**Comment by maehw** [comment] 2021-11-18 20:28
Hi Clemens,

thank you for the update and for granting me the rights.

>As for the discussions, I think we should try the GitHub discussions page. I have also enabled the feature for this repo. This way other people can read the messages and maybe can get some info out of it.

OK, sure. Let's try this out. Haven't worked with discussion pages on GitHub yet so I might need some kind of "warm-up phase". E.g. what's worth a new, separate discussion and what should be kept together?

>The only drawback that I see is that I don't get a push message to my desktop for GitHub notifications and I check my emails once a day at most. I'll get the GitHub mobile app and try to answer in a timely manner.
Would this be alright for you or do you have another idea how we could handle discussions better? An open discord server is another alternative that I can think of, but I don't know if that's worth for two people..

No worries. We all have other things to do. I also will not check my mail every day or even reply as often. ;) I'm not using Discord too often. Let's start here and see how we get on.

Greetings,
maehw

**Comment by ClemensElflein** [comment] 2021-11-18 22:19
I think the original issue has been answered by @maehw and we can close this here since further discussion should happen elsewhere.

**Closed by ClemensElflein** 2021-11-18 22:19 UTC
